version: '3'

services:
  db:
    image: postgres
    volumes:
      - /init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  app:
    build: /python
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: python app.py
    ports:
      - "5000:5000"